package br.com.gabriel.planetsinfo.model

import br.com.gabriel.planetsinfo.R

object PlanetaRepository {

    fun getAll(): List<Planeta>{
        return listOf(
             Planeta("Mercúrio","Planeta","mercurio","Mercúrio é o menor e mais interno planeta do Sistema Solar, orbitando o Sol a cada 87,969 dias terrestres. A sua órbita tem a maior excentricidade e o seu eixo apresenta a menor inclinação em relação ao plano da órbita dentre todos os planetas do Sistema Solar. Mercúrio completa três rotações em torno de seu eixo a cada duas órbitas. O periélio da órbita de Mercúrio apresenta uma precessão de 5 600 segundos de arco por século, um fenômeno completamente explicado apenas a partir do século XX pela Teoria da Relatividade Geral formulada por Albert Einstein. A sua aparência é brilhante quando observado da Terra, tendo uma magnitude aparente que varia de −2,6 a 5,7, embora não seja facilmente observado pois sua separação angular do Sol é de apenas 28,3º. Uma vez que Mercúrio normalmente se perde no intenso brilho solar, exceto em eclipses solares, só pode ser observado a olho nu durante o crepúsculo matutino ou vespertino.")
            ,Planeta("Vénus","Planeta","venus","Vénus (português europeu) ou Vênus (português brasileiro) (AO 1990: Vénus ou Vênus) é o segundo planeta do Sistema Solar em ordem de distância a partir do Sol, orbitando-o a cada 224,7 dias. Recebeu seu nome em homenagem à deusa romana do amor e da beleza Vénus, equivalente a Afrodite. Depois da Lua, é o objeto mais brilhante do céu noturno, atingindo uma magnitude aparente de -4,6, o suficiente para produzir sombras. A distância média da Terra a Vênus é de 0,28 AU, sendo esta a menor distância entre qualquer par de planetas. Como Vénus se encontra mais próximo do Sol do que a Terra, ele pode ser visto aproximadamente na mesma direção do Sol (sua maior elongação é de 47,8°). Vénus atinge seu brilho máximo algumas horas antes da alvorada ou depois do ocaso, sendo por isso conhecido como a estrela da manhã (Estrela d'Alva) ou estrela da tarde (Vésper); também é chamado Estrela do Pastor.")
            ,Planeta("Terra","Planeta","terra","A Terra é o terceiro planeta mais próximo do Sol, o mais denso e o quinto maior dos oito planetas do Sistema Solar. É também o maior dos quatro planetas telúricos. É por vezes designada como Mundo ou Planeta Azul. Lar de milhões de espécies de seres vivos, incluindo os humanos, a Terra é o único corpo celeste onde é conhecida a existência de vida. O planeta formou-se há 4,56 bilhões de anos, e a vida surgiu na sua superfície um bilhão de anos depois. Desde então, a biosfera terrestre alterou significativamente a atmosfera e outros fatores abióticos do planeta, permitindo a proliferação de organismos aeróbicos, bem como a formação de uma camada de ozônio, a qual, em conjunto com o campo magnético terrestre, bloqueia radiação solar prejudicial, permitindo a vida no planeta. As propriedades físicas do planeta, bem como sua história geológica e órbita, permitiram que a vida persistisse durante este período. Acredita-se que a Terra poderá suportar vida durante pelo menos outros 500 milhões de anos.")
            ,Planeta("Marte","Planeta","marte","Marte é um planeta rochoso com uma atmosfera fina, com características de superfície que lembram tanto as crateras de impacto da Lua quanto vulcões, vales, desertos e calotas polares da Terra. O período de rotação e os ciclos sazonais de Marte são também semelhantes aos da Terra, assim como é a inclinação que produz as suas estações do ano. Marte é o lar do Monte Olimpo, a segunda montanha mais alta conhecida no Sistema Solar (a mais alta em um planeta), e do Valles Marineris, um desfiladeiro gigantesco. A suave Bacia Polar Norte, no hemisfério norte marciano, cobre cerca de 40% do planeta e pode ser uma enorme marca de impacto. Marte tem duas luas conhecidas, Fobos e Deimos, que são pequenas e de forma irregular. Estas luas podem ser asteroides capturados, semelhante ao 5261 Eureka, um asteroide troiano marciano.")
            ,Planeta("Jupter","Planeta","jupter","Júpiter é o maior planeta do Sistema Solar, tanto em diâmetro quanto em massa, e é o quinto mais próximo do Sol. Possui menos de um milésimo da massa solar, contudo tem 2,5 vezes a massa de todos os outros planetas em conjunto. É um planeta gasoso, junto com Saturno, Urano e Netuno. Estes quatro planetas são por vezes chamados de planetas jupiterianos ou planetas jovianos, e são os quatro gigantes gasosos, isto é, que não são compostos primariamente de matéria sólida.")
            ,Planeta("Saturno","Planeta","saturno","Saturno é o sexto planeta a partir do Sol e o segundo maior do Sistema Solar atrás de Júpiter. Pertencente ao grupo dos gigantes gasosos, possui cerca de 95 massas terrestres e orbita a uma distância média de 9,5 unidades astronômicas. Possui um pequeno núcleo rochoso, circundado por uma espessa camada de hidrogênio metálico e hélio. A sua atmosfera, também composta principalmente de hidrogênio, apresenta faixas com fortes ventos, cuja energia provém tanto do calor recebido do Sol quanto da energia irradiada de seu centro. Entretanto, estas bandas possuem aspecto pouco proeminente, com coloração que varia do marrom ao amarelado, devido à espessa névoa que envolve o planeta, além das camadas de nuvens. Sazonalmente surgem grandes sistemas de tempestades, além de vórtices permanentes existentes nos polos.")
            ,Planeta("Urano","Planeta","urano","Urano (Úrano em Portugal) é o sétimo planeta a partir do Sol, o terceiro maior e o quarto mais massivo dos oito planetas do Sistema Solar. Foi nomeado em homenagem ao deus grego do céu, Urano, o pai de Cronos (Saturno) e o avô de Zeus (Júpiter). Embora seja visível a olho nu em boas condições de visualização, não foi reconhecido pelos astrônomos antigos como um planeta devido a seu pequeno brilho e lenta órbita. William Herschel anunciou sua descoberta em 13 de março de 1781, expandindo as fronteiras do Sistema Solar pela primeira vez na história moderna. Urano foi também o primeiro planeta a ser descoberto por meio de um telescópio.")
            ,Planeta("Neturno","Planeta","neturno","Netuno ou Neptuno (AO 1990: Netuno ou Neptuno) é o oitavo planeta do Sistema Solar, o último a partir do Sol desde a reclassificação de Plutão para a categoria de planeta anão, em 2006. Pertencente ao grupo dos gigantes gasosos, possui um tamanho ligeiramente menor que o de Urano, mas maior massa, equivalente a 17 massas terrestres. Netuno orbita o Sol a uma distância média de 30,1 unidades astronômicas. O planeta é formado por um pequeno núcleo rochoso ao redor do qual encontra-se uma camada formada possivelmente por água, amônia e metano sobre a qual situa-se sua turbulenta atmosfera, constituída predominantemente de hidrogênio e hélio. De fato, notáveis eventos climáticos ocorrem em Netuno, inclusive a formação de diversas camadas de nuvens, tempestades ciclônicas visíveis, como a já extinta Grande Mancha Escura, além dos ventos mais rápidos do Sistema Solar, que atingem mais de 2 000 km/h. A radiação solar recebida por Netuno não seria suficiente para fornecer tamanha energia à turbulenta atmosfera, pelo que descobriu-se que o calor irradiado do centro do planeta possui um papel importante na manutenção destes eventos meteorológicos extremos. A pequena quantidade de metano nas camadas altas da atmosfera é, em parte, responsável pela coloração azul do planeta.")
            ,Planeta("Ceres","Planeta Anão", "ceres","Ceres (na designação de planeta menor 1 Ceres) é um planeta anão localizado no cinturão de asteroides entre Marte e Júpiter, sendo o maior dos asteroides. Desde sua descoberta em janeiro de 1801 por Giuseppe Piazzi, Ceres recebeu diversas classificações, sendo inicialmente considerado planeta e posteriormente asteroide. Em 2006 foi enquadrado na categoria de planeta anão.")
            ,Planeta("Plutão","Planeta Anão","plutao","Plutão, formalmente designado 134340 Plutão, é um planeta anão do Sistema Solar e o nono maior e décimo mais massivo objeto observado diretamente orbitando o Sol. Originalmente classificado como um planeta, Plutão é atualmente o maior membro conhecido do cinturão de Kuiper, uma região de corpos além da órbita de Netuno.")
            ,Planeta("Haumea","Planeta Anão","haumea","Haumea, com a designação de planeta menor 136108 Haumea, antes conhecido astronomicamente como 2003 EL61, é um planeta anão do tipo plutoide, localizado a 43,3 UA do Sol, ou seja um pouco mais de 43 vezes a distância da Terra ao Sol, em pleno Cinturão de Kuiper. Haumea possui dois pequenos satélites naturais, Hiʻiaka e Namaka, que, acredita-se, sejam destroços que se separaram de Haumea devido a uma antiga colisão. É o objeto astronômico com a mais rápida rotação no Sistema Solar, durando apenas quatro horas, o que faz com que o planeta-anão seja extremamente deformado, sendo semelhante a uma bola de rugby. Além disso, possui um albedo elevado devido a presença de gelo em forma cristalina na superfície. Pensa-se, também, tratar-se do maior membro de uma família de destroços criados num único evento destrutivo.")
            ,Planeta("Makemake","Planeta Anão","makemake","Makemake, formalmente designado como (136472) Makemake, é o terceiro maior planeta anão do Sistema Solar e o maior objeto transnetuniano conhecido na população dos cubewanos, com um diâmetro de cerca de dois terços o de Plutão. Possui um satélite conhecido, o S/2015 (136472) 1. Sua superfície é coberta por metano, etano e possivelmente nitrogênio e tem uma baixa temperatura média de cerca de 30 K (-243,2 °C).")
            ,Planeta("Éris","Planeta Anão","eris","136199 Eris (designação de planeta menor), ou Éris ou informalmente conhecido Décimo Planeta, é um planeta anão plutoide situado nos confins do sistema solar, em uma distância de 97 UA do Sol, em seu afélio, em uma região conhecida como disco disperso. Quando foi descoberto, ficou desde logo informalmente conhecido como o 'décimo planeta', porque na época seu diâmetro estimado era maior do que o diâmetro do planeta-anão Plutão.")
            , Planeta("Dysnomia","Planeta Anão","dysnomia","Disnomia é o satélite natural de Éris. O nome significa 'desordem' em grego (no original, Δυσνομία dysnomia), uma referência à entidade mitológica que, segundo Hesíodo, era filha de Éris, a Discórdia. Em 2005, uma equipe nos telescópios Keck no Havaí fez observações aos quatro corpos celestes transneptunianos mais brilhantes (Plutão, 2005 FY9, 2003 EL61 e Éris) usando um novo sistema óptico. Em 10 de Setembro, as observações revelaram uma lua orbitando Éris. Na altura da descoberta, Éris não tinha nome e era conhecida, popularmente, como Xena, assim a lua ganhou a alcunha de Gabrielle pelos seus descobridores, a companheira de Xena na série televisiva Xena, A Princesa Guerreira.")
        )
    }
}